export const authToken =
  'Bearer ' +
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Ijk5YjJjMGYwMGEyMzQ5ZWZiNzdkMjA4YzdmMzFlYTYyIiwiYXVkIjoiaHR0cHM6Ly80cWJveWswNzQyLmV4ZWN1dGUtYXBpLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tL3Byb2QvIiwiaWF0IjoxNjQ3MTc4NDc4LCJleHAiOjE2NTQ5NTQ0Nzh9.83a3PuIxZVZGWdaoO3q3Rx3lHmcsxT0UFjiJ0jiuaSM';

export const videoItems = [
  {mediaId: 'ufEqIjHB'},
  {mediaId: 'XFmcLkVD'},
  {mediaId: 'mcslliLu'},
  {mediaId: 'hKXEbFwp'},
  {mediaId: '1TtNHU7x'},
  {mediaId: '8LyOizOc'},
  {mediaId: 'xnzeXrNL'},
  {mediaId: 'KvXfwMWL'},
  {mediaId: 'oMTFmL7q'},
  {mediaId: 'VZxG3dvC'},
  {mediaId: 'CM3yWwtZ'},
  {mediaId: '0KW9B2HU'},
  {mediaId: 'yAXjYLsi'},
  {mediaId: '9pOToEir'},
  {mediaId: 'fRAtgEvT'},
  {mediaId: 'DmiImzhQ'},
  {mediaId: 'ernhsTHy'},
  {mediaId: 'xfBqKWSA'},
  {mediaId: 'Zbj7IaQW'},
  {mediaId: 'PMPAZkJj'},
  {mediaId: 'axOUUn48'},
  {mediaId: 'iMVbQnbQ'},
  {mediaId: 'Fr6l4vsl'},
  {mediaId: 'JcxH72sw'},
  {mediaId: 'Cts8Wydw'},
  // page 2
  {mediaId: 'ltqJbZRa'},
  {mediaId: 'cK83ywCr'},
  {mediaId: 'cO2owKkQ'},
  {mediaId: 'cYV6fIiC'},
  {mediaId: 'kn4Wza5e'},
  {mediaId: 'VbQAKquX'},
  {mediaId: 'pNZ6U8RR'},
  {mediaId: '7Uvz1yvM'},
  {mediaId: 'Z76nAEEw'},
  {mediaId: 'cgNwkPEM'},
  {mediaId: 'o66xGGWJ'},
  {mediaId: 'KH4I7p1E'},
  {mediaId: 'Zq7fuENY'},
  {mediaId: '1L0TMQXs'},
  {mediaId: 'uc66oOpj'},
  {mediaId: 'fRAtgEvT'},
  {mediaId: 'jfFjO3mk'},
  {mediaId: '3IF6Ovzk'},
  {mediaId: 'wpA5m2qo'},
  {mediaId: 'PK6XUyPI'},
  {mediaId: '3GEmKLDg'},
  {mediaId: 'sNlrR46t'},
  {mediaId: 'DisYfKzv'},
  {mediaId: 'IBlsFOcf'},
  {mediaId: '11tYh054'},
  // page 3
  {mediaId: 'GOmcNviu'},
  {mediaId: 'G8nYyMke'},
  {mediaId: 'XaEOskmh'},
  {mediaId: 'DbyFsEJq'},
  {mediaId: 'IiyRC4YQ'},
  {mediaId: 'oMlZpiU8'},
  {mediaId: 'xVK0IGlk'},
  {mediaId: 'dy7vy0zv'},
  {mediaId: 'tmXVfF1S'},
  {mediaId: 'bjb7aYl7'},
  {mediaId: 'tfVpPHSP'},
  {mediaId: 'O1qBwdz4'},
  {mediaId: 'Jm9UuFLT'},
  {mediaId: 'LM25fsSr'},
  {mediaId: 'kjMvVqP9'},
  {mediaId: 'ehSToGgj'},
  {mediaId: 'OPMMjVuO'},
  {mediaId: 'CQ9HbeZw'},
  {mediaId: 'YIC0dy5z'},
  {mediaId: 'IE3TFFWc'},
  {mediaId: 'NoFNnxq1'},
  {mediaId: 'KH4I7p1E'},
  {mediaId: 'gSpEHDb5'},
  {mediaId: 'q0Im68b5'},
  {mediaId: 'XPHYZsfg'},
].map((i, index) => ({
  key: index,
  mediaId: i?.mediaId,
}));

export default {
  authToken,
  videoItems,
};
